all: 00_pe_return_00.exe \
     00_pe_return_01.exe \
     00_pe_return_02.exe \
     00_pe_return_03.exe \
     00_pe_return_04.exe \
     00_pe_return_05.exe \
     00_pe_return_06.exe \
     01_pe_printf_00.exe \
     01_pe_printf_01.exe \
     01_pe_printf_02.exe \
     02_pe_messagebox_00.exe \
     02_pe_messagebox_01.exe \
     02_pe_messagebox_02.exe \
     02_pe_messagebox_03.exe

00_pe_return_00.exe: 00_pe_return_00.asm
	fasm 00_pe_return_00.asm

00_pe_return_01.exe: 00_pe_return_01.asm
	fasm 00_pe_return_01.asm

00_pe_return_02.exe: 00_pe_return_02.asm
	fasm 00_pe_return_02.asm

00_pe_return_03.exe: 00_pe_return_03.asm
	fasm 00_pe_return_03.asm

00_pe_return_04.exe: 00_pe_return_04.asm
	fasm 00_pe_return_04.asm

00_pe_return_05.exe: 00_pe_return_05.asm
	fasm 00_pe_return_05.asm

00_pe_return_06.exe: 00_pe_return_06.asm
	fasm 00_pe_return_06.asm

01_pe_printf_00.exe: 01_pe_printf_00.asm
	fasm 01_pe_printf_00.asm

01_pe_printf_01.exe: 01_pe_printf_01.asm
	fasm 01_pe_printf_01.asm

01_pe_printf_02.exe: 01_pe_printf_02.asm
	fasm 01_pe_printf_02.asm

02_pe_messagebox_00.exe: 02_pe_messagebox_00.asm
	fasm 02_pe_messagebox_00.asm

02_pe_messagebox_01.exe: 02_pe_messagebox_01.asm
	fasm 02_pe_messagebox_01.asm

02_pe_messagebox_02.exe: 02_pe_messagebox_02.asm
	fasm 02_pe_messagebox_02.asm

02_pe_messagebox_03.exe: 02_pe_messagebox_03.asm
	fasm 02_pe_messagebox_03.asm
